---
output: pdf_document
---


```{r setup, echo=FALSE, results=FALSE}
knitr::opts_chunk$set(fig.height=3, comment="#")
```



Sonish Lamsal / Bradley Thompson

STA6375: Computational Statistics I

\begin{center}
Homework 3
\end{center}

```{r echo=FALSE}
options(
ggplot2.continuous.colour = "viridis",
ggplot2.continuous.fill = "viridis",
ggplot2.discrete.colour = "brewer",
ggplot2.discrete.fill = "brewer"
)
```


1a.

```{r, message=FALSE}
library("tidyverse")



df <- expand.grid("x" = 1:10, "y" = 1:10) 
ggplot(df, aes(x, y)) +
  geom_point() +
  theme_minimal()

```

1b. 

```{r, message=FALSE}
ggplot(df, aes(x, y)) +
  geom_point() +
  theme_minimal() +
  coord_equal()
```


1c.
```{r}
set.seed(1)
fuzz <- rnorm(nrow(df))
  ggplot(df,aes(x,y)) + 
  geom_raster(aes(fill=fuzz))+
  theme_minimal()
```

1d.
```{r}
ggplot(df,aes(x,y)) + 
  geom_raster(aes(fill=fuzz)) + 
  theme_minimal() +
  theme(legend.position="none") +
  coord_equal() 
```

1e
```{r}
ggplot(df, aes(x = x, y = y)) +
  geom_raster(aes(fill = fuzz)) + 
  scale_fill_gradient(low = "black", high = "white") + 
  coord_equal() + 
  theme_light() +
  theme(legend.position = "none")

```

1f.
```{r}
ggplot(df, aes(x = x, y = y)) +
  geom_tile(aes(fill = fuzz)) + 
  scale_fill_gradient(low = "black", high = "white") + 
  coord_equal() + 
  theme_void() +
  theme(legend.position = "none")
```

1g
```{r}
x<- seq(0,1, length.out=1001)
FX <- sinpi(2*x)
values<- data.frame(x=c(x),y=c(FX))
ggplot(values,aes(x,y)) + 
  geom_line() + 
  xlim(0,1) + 
  ylim(-1,1) +
  theme_minimal() +
  ylab("fx")
```

1h
```{r}
ggplot(values,aes(x,y)) + 
  geom_ribbon(aes(ymin=y-0.2,ymax=y+0.2),fill="grey50")+
  geom_line(aes(y=y),colour="green") +
  xlim(0,1) + 
  ylim(-1.2,1.2) +
  theme_minimal() +
  ylab("fx")
```

1i
```{r}
x<- vector()
y<-vector()
for (i in 1:10) {
  x[i]=cos((i-1)*36*pi/180)
  y[i]=sin((i-1)*36*pi/180)
}
df<- data.frame(x=x,y=y)
ggplot(df,aes(x,y))+
  geom_polygon(colour="black",fill=NA)+
  theme_minimal()+
  geom_point()+
  coord_equal()
```

1j
```{r}
set.seed(1)
df<- data.frame(x=rnorm(1e3, mean= 3, sd=2 ))
  ggplot(df, aes(x)) +
  geom_density() + 
  stat_function(fun=dnorm, args = list(mean=3, sd=2), colour = "red")+
  geom_vline(xintercept = 8, colour="red", linetype="twodash") +
  theme_minimal()

```

2a.
```{r}
# A <- matrix(c(1,3,2,-7,9,1,-2,2,4), nrow = 3, byrow = TRUE)
# ev <- eigen(A)
# V <- ev$vectors
# L <- ev$values
# Lamda <- matrix(c(0,0,0,0,0,0,0,0,0), nrow = 3)
# for(i in 1:length(L)){
#   Lamda[i,i] <- L[i]
# }
# V_1 <- solve(V)
# A
# V %*% Lamda %*% V_1
A <- matrix(c(-1,3,1,
              -7,9,1,
              -2,2,4), nrow = 3, byrow = TRUE)
ev <- eigen(A)
V <- ev$vectors
L <- ev$values
Lamda <- diag(L)
V_1 <- solve(V)
A
V %*% Lamda %*% V_1
```

2b.
```{r}
A <- matrix(c(10,2,-6,2,7,0,-6,0,2), nrow = 3, byrow = TRUE)
ev <- eigen(A)
V <- ev$vectors
L <- ev$values
Lamda <- diag(L)
VT <-t(V)
A
zapsmall(V %*% Lamda %*% VT)
zapsmall(crossprod(V))
```

2c.
```{r}
A <- matrix(c(1,2,3,4,5,6,7,8,6,8,10,12), nrow = 4, byrow = FALSE)
s_v_d <- svd(A)
U <- s_v_d$u
D <- s_v_d$d
E <- diag(D)
V <- s_v_d$v
A
zapsmall(U %*% E %*% t(V))
```

2d.
```{r}
A <- matrix(c(4,2,1,
              2,4,2,
              1,2,4), nrow = 3, byrow = TRUE)
ev <- eigen(A)
ev
#you can do a Cholesky decomposition of A becasue A is positive definite since
#all of its eigenvalues are positive and it's symmetric
C <- chol(A)
C
A
t(C) %*% C
```

2e
```{r}
A <- matrix(c(4,2,1,
              2,4,2,
              1,2,4), nrow = 3, byrow = TRUE)
ev <- eigen(A)
ev
#you can do a Cholesky decomposition of A becasue A is positive definite since
#all of its eigenvalues are positive and it's symmetric
B<- matrix(nrow=3,ncol=3)
for (i in 1:3) {
  for (j in 1:i) {
    sum <- 0
    if (i==j){
      for (k in 1:j) {
        sum<- sum + B[j,k]^2
      }
        B[j,j]=(A[j,j]-sum)^(1/2)
    }
    else{
      for (l in 1:j) {
        sum = (B[i,k]*B[j,k])
      }
      B[i,j] = (A[i,j]-sum)/A[j,j]
    }
    
  }
}
B


```


